### ISSUE TITLE
i need your help pls

### ISSUE THREAD

**Issue by AniverseUZ** [rahulps1000/rahulps1000#7]
i created your file sharing bot. it working but i want to add 4 force channels

**Comment by rahulps1000** [comment]
You can modify the code and add 4 force sub channels. But I won't support it. Forcing users to join one channel is okay, but more than that is too much.

**Comment by AniverseUZ** [comment]
> You can modify the code and add 4 force sub channels. But I won't support it. Forcing users to join one channel is okay, but more than that is too much.

Pls i need this
